sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t pengwang/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pengwang/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-bigbear"
  env: "Dockerreactbigbear-env"
  bucket_name: "elasticbeanstalk-us-east-1-814337578461"
  bucket_path: "docker-react-bigbear"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY