language: generic 
sudo:required
services:
  - docker

before_install:
  - docker build -t pengwang/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pengwang/docker-react npm run test